cd "$(dirname $0)"
python -u ../src/main.py \
    --model agdn \
    --sample-type random_cluster \
    --train-partition-num 6 \
    --eval-partition-num 2 \
    --eval-times 1 \
    --lr 0.01 \
    --advanced-optimizer \
    --n-epochs 2000 \
    --n-heads 6 \
    --n-layers 6 \
    --weight-style HC \
    --dropout 0.4 \
    --n-hidden 150 \
    --input-drop 0.1 \
    --attn-drop 0. \
    --hop-attn-drop 0. \
    --edge-drop 0.1 \
    --norm none \
    --K 2 \
    --gpu 0 