cd "$(dirname $0)" 
python -u ../../src/main.py \
    --seed 0 \
    --n-label-iters 0 \
    --lr 0.002 \
    --standard-loss \
    --model gcn-ha \
    --mode test \
    --n-layers 3 \
    --n-hidden 256 \
    --K 3 \
    --n-heads 3 \
    --dropout 0.75 \
    --input_drop 0.25 \
    --edge_drop 0.3\
    --attn_drop 0. \
    --norm none \
    --n-epochs 2000 \
    --n-runs 10 \
    --mask-rate 0 \
    --gpu 0